name: lolipop
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
          run: composer install
          working-directory: ./loadmap
        
      - name: php artisan config:cache
        run: php artisan config:cache
        working-directory: ./loadmap
      
      -name: php artisan route:cache
        run: php artisan route:cache
        working-directory: ./loadmap

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./